# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Sergio Durigan Junior
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure SearXNG paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ searxng_uid }}"
    group: "{{ searxng_gid }}"
  with_items:
    - "{{ searxng_base_path }}"
    - "{{ searxng_cache_path }}"
    - "{{ searxng_data_path }}"

- name: Ensure SearXNG support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ searxng_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ searxng_uid }}"
    group: "{{ searxng_gid }}"
  with_items:
    - env
    - labels

- name: Ensure settings.yml for SearXNG installed
  ansible.builtin.copy:
    content: "{{ searxng_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ searxng_data_path }}/settings.yml"
    mode: "0640"
    owner: "{{ searxng_uid }}"
    group: "{{ searxng_gid }}"

- name: Ensure limiter.toml for SearXNG installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ searxng_data_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ searxng_uid }}"
    group: "{{ searxng_gid }}"
  with_items:
    - limiter.toml

- name: Run if self-building of SearXNG container image is not enabled
  when: "not searxng_container_image_self_build | bool"
  block:
    - name: Ensure SearXNG container image is pulled via community.docker.docker_image
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ searxng_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ searxng_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else searxng_container_image_force_pull }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed

    - name: Ensure SearXNG container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ searxng_container_image }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed
      changed_when: "'Downloaded newer image' in result.stdout"

- name: Run if self-building of SearXNG container image is enabled
  when: "searxng_container_image_self_build | bool"
  block:
    - name: Ensure SearXNG repository is present on self-build
      ansible.builtin.git:
        repo: "{{ searxng_container_image_self_build_repo }}"
        version: "{{ searxng_container_image_self_build_repo_version }}"
        dest: "{{ searxng_container_image_self_build_src_files_path }}"
        force: "yes"
      register: searxng_git_pull_results

    - name: Ensure SearXNG container image is built
      community.docker.docker_image:
        name: "{{ searxng_container_image_self_build_name }}"
        source: build
        force_source: "{{ searxng_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else searxng_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ searxng_container_image_self_build_src_files_path }}"
          pull: true
          args:
      register: searxng_container_image_build_result

- name: Ensure SearXNG container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ searxng_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: searxng_network_creation_result

- name: Ensure SearXNG container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ searxng_container_network }}
  register: searxng_network_creation_result
  changed_when: searxng_network_creation_result.rc == 0
  failed_when: searxng_network_creation_result.rc != 0 and 'already exists' not in searxng_network_creation_result.stderr

- name: Ensure SearXNG systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/searxng.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ searxng_identifier }}.service"
    mode: "0644"
